### PR TITLE
Propagate the nixpkgs dependency to reduce the amount of nixpkgs instances.

### PR DESCRIPTION
**Pull request by R-VdP**

### CODE REVIEW

**Comment by domenkozar** [comment]
I pushed a fix into `relaxed-flakes`, so if you `devenv update` and `nix flake update`, CI should pass again.

**Comment by domenkozar** [comment]
It's weird this fails and https://github.com/NixOS/nix/pull/7367 succeeds. Needs investigation :)

**Comment by R-VdP** [comment]
But that PR also removes the boehm patch, so I guess we'd have to do the same in the `relaxed-flakes` branch to get it to work with 22.11+.

**Comment by domenkozar** [comment]
Pushed a removal of the boehm patch

**Pull request merged**
