### PR TITLE
Add support for `uv` project management

### PR DESCRIPTION
**Pull request by lamalex**
Adds support to python.nix to use `uv sync` when enabled and `uv` >= 0.4.4
`uv` 0.4.4 is the first version to respect `UV_PROJECT_ENVIRONMENT` which
allows `uv` to play nicely with the venv created by devenv (not `.venv`)

### CODE REVIEW

**Comment by domenkozar** [comment]
Looks like a great start :) Thank you so much!

Could you also add a test to `tests`?

**Comment by lamalex** [comment]
How do I generate docs so that check will pass?

**Comment by domenkozar** [comment]
```
Error: Error: Pushing to https://github.com/lamalex/devenv
remote: Permission to lamalex/devenv.git denied to github-actions[bot].
fatal: unable to access 'https://github.com/lamalex/devenv/': The requested URL returned error: 403
```

@sandydoo I think we've enabled this for PRs, but we'd have to target upstream branch for it to work.

**Comment by domenkozar** [comment]
@lamalex 

```
       error: at /run/github-runner/cachix-x86_64-linux/devenv/devenv/tests/python-uv-sync/devenv.nix:2:1:
            1| { pkgs, config, ... }:
            2| : let
             | ^
            3| pkgs-unstable = import inputs.nixpkgs-unstable { system = pkgs.stdenv.system; };

       error: syntax error, unexpected ':'
```

**Comment by domenkozar** [comment]
Seems like we need to commit the initial `uv.lock`.

I've merged this manually, thank you!

**Pull request closed without merging**
