### PR TITLE
mongodb: initial user creation

### PR DESCRIPTION
**Pull request by samjwillis97**
Addressing issue #672.

This allows the creation of an initial user with password in MongoDB.

### CODE REVIEW

**Comment by domenkozar** [comment]
Nice! Could you write a little test so we can be aire it works?

See `.test.sh` files in other examples.

**Comment by samjwillis97** [comment]
Sure can 😄

**Comment by samjwillis97** [comment]
I've added a test for MongoDB with initial user creation, let me know if there are any other changes

**Comment by stig** [comment]
I'm giving this a spin locally :-)

**Review by stig — APPROVED** [review]
I've tested this locally and it works for my use case 👍🏼

**Comment by samjwillis97** [comment]
Thats great to hear, I'm glad

**Comment by domenkozar** [comment]
It seems that the tests are stuck, maybe you can take a look?

**Comment by samjwillis97** [comment]
I think its still in the build step.. the nscloud-arm64 failed whilst building 2 hours in

**Comment by samjwillis97** [comment]
So it looks like it was the build step, both `macos-latest` and `self-hosted, macOS` tests passed, but the `ubuntu-latest` and `nscloud-arm64` ran out of space whilst building 😕

**Comment by domenkozar** [comment]
I pushed a fix to `main`, could you rebase and let's see if it works?

**Comment by samjwillis97** [comment]
just rebased it, ready to give it another go :crossed_fingers:

**Comment by samjwillis97** [comment]
Looks like we're getting the same failures :disappointed:
Would it be an option to build mongo out of the actions and push up to cachix? Although when there are changes to the mongo package this problem will arise again..

**Comment by domenkozar** [comment]
Let's try giving it more space, could you add this action instead of my `rm -rf /opt` hack?

```
- name: Maximize build space
        uses: easimon/maximize-build-space@master
        with:
          remove-dotnet: true
          remove-android: true
          remove-codeql: true
```

**Comment by samjwillis97** [comment]
Alright, thats in there now

**Comment by domenkozar** [comment]
> /Users/runner/work/_temp/01d09040-1cc8-4083-b06d-97ad163b6af8.sh: line 2: free: command not found

**Comment by domenkozar** [comment]
Do you need help here?

**Comment by samjwillis97** [comment]
I need to get my head back into this and have a look around with what we can do, I will let you know how I go

**Comment by samjwillis97** [comment]
Finally getting back into this. Turns out the `maximize-build-space` action only support linux as mentioned in this issue https://github.com/easimon/maximize-build-space/issues/7./

It was the `ubuntu-latest` and `nscloud-arm64` that have been running out of storage, so we could conditionally run the action for `ubuntu-latest` runners? This still doesn't solve for `nscloud-arm64` which looks to start with 55GB space which I would have thought was plenty 😞

I'm also a bit confused about the `ubuntu-latest` runners because none of their tests passed either, but I'm unable to find a clear reason for the failure - the logs I have looked through are pretty clear, was it potentially caused by the actions being cancelled? or am I missing something?

**Comment by domenkozar** [comment]
Could you rebase and let's give it another go?

**Comment by domenkozar** [comment]
@samjwillis97 could you rebase again please? :)

**Comment by samjwillis97** [comment]
I'll give it a go today :)

**Comment by domenkozar** [comment]
Do you know if mongodb is fixed now?

**Comment by samjwillis97** [comment]
I'm not sure.. I just had a quick look through nixpkgs issues and couldn't see any talk around mongodb 6 being broken, but it was bumped from 6.0.12 to 6.0.13 just 5 days ago

**Comment by domenkozar** [comment]
Could you rebase, maybe it will finally build :)

**Comment by samjwillis97** [comment]
We can only hope at this point 🤞

**Comment by domenkozar** [comment]
@samjwillis97 is seems like you'll need to run `pre-commit run -a`

**Pull request merged**
