### PR TITLE
Support OCaml

### PR DESCRIPTION
**Pull request by domenkozar**

### CODE REVIEW

**Comment by terlar** [comment]
I was just trying out this integration and it seems somehow the hooks or environment variables populated by the hook `pkgs.ocamlPackages.findlib` propagates.

If I execute this in a shell:
```
$ nix-shell -p ocamlPackages.findlib ocamlPackages.ounit
$ echo $OCAMLPATH 
/nix/store/wapb2335lpzyawb7ycr43ql06bvz8bcj-ocaml4.14.0-findlib-1.9.6/lib/ocaml/4.14.0/site-lib/ /nix/store/cvsrfpjql77p2i9wkwrvkmh1gbgz8hkq-ocaml4.14.0-ounit-2.2.6/lib/ocaml/4.14.0/site-lib/ /nix/store/3gy53ldj4sg40jvfjs77hhrmyinc4fa1-ocaml4.14.0-ounit2-2.2.6/lib/ocaml/4.14.0/site-lib/ /nix/store/5l37rgnwr7giykyvh00aw08gznmqc4bl-ocaml4.14.0-seq-0.1/lib/ocaml/4.14.0/site-lib/ /nix/store/ww9dhf42h5r07yzmzwg4g1ay691f3qxl-ocaml4.14.0-stdlib-shims-0.3.0/lib/ocaml/4.14.0/site-lib/
$ echo $OCAMLFIND_DESTDIR 
/nix/store/jrwx7himsidf8aaiflvzh9mjlhrrgy1p-shell/lib/ocaml/4.14.0/site-lib/
```

However using devenv like this:
```
{ pkgs, ... }: {
  languages.ocaml.enable = true;

  packages = [
    # Used to setup the OCAMLPATH for libs
    pkgs.ocamlPackages.findlib

    # Libs
    pkgs.ocamlPackages.base
    pkgs.ocamlPackages.core_kernel
    pkgs.ocamlPackages.ounit
    pkgs.ocamlPackages.qcheck

    # REPL
    pkgs.ocamlPackages.utop
  ];
}
```

and then if I check the environment variable `OCAMLPATH` in the shell it is not set. I guess I should open a ticket for this, just wonder if this is something I'm doing wrong?

**Comment by thenonameguy** [comment]
> I was just trying out this integration and it seems somehow the hooks or environment variables populated by the hook `pkgs.ocamlPackages.findlib` propagates.
> 
> 
> 
> If I execute this in a shell:
> 
> ```
> 
> $ nix-shell -p ocamlPackages.findlib ocamlPackages.ounit
> 
> $ echo $OCAMLPATH 
> 
> /nix/store/wapb2335lpzyawb7ycr43ql06bvz8bcj-ocaml4.14.0-findlib-1.9.6/lib/ocaml/4.14.0/site-lib/ /nix/store/cvsrfpjql77p2i9wkwrvkmh1gbgz8hkq-ocaml4.14.0-ounit-2.2.6/lib/ocaml/4.14.0/site-lib/ /nix/store/3gy53ldj4sg40jvfjs77hhrmyinc4fa1-ocaml4.14.0-ounit2-2.2.6/lib/ocaml/4.14.0/site-lib/ /nix/store/5l37rgnwr7giykyvh00aw08gznmqc4bl-ocaml4.14.0-seq-0.1/lib/ocaml/4.14.0/site-lib/ /nix/store/ww9dhf42h5r07yzmzwg4g1ay691f3qxl-ocaml4.14.0-stdlib-shims-0.3.0/lib/ocaml/4.14.0/site-lib/
> 
> $ echo $OCAMLFIND_DESTDIR 
> 
> /nix/store/jrwx7himsidf8aaiflvzh9mjlhrrgy1p-shell/lib/ocaml/4.14.0/site-lib/
> 
> ```
> 
> 
> 
> However using devenv like this:
> 
> ```
> 
> { pkgs, ... }: {
> 
>   languages.ocaml.enable = true;
> 
> 
> 
>   packages = [
> 
>     # Used to setup the OCAMLPATH for libs
> 
>     pkgs.ocamlPackages.findlib
> 
> 
> 
>     # Libs
> 
>     pkgs.ocamlPackages.base
> 
>     pkgs.ocamlPackages.core_kernel
> 
>     pkgs.ocamlPackages.ounit
> 
>     pkgs.ocamlPackages.qcheck
> 
> 
> 
>     # REPL
> 
>     pkgs.ocamlPackages.utop
> 
>   ];
> 
> }
> 
> ```
> 
> 
> 
> and then if I check the environment variable `OCAMLPATH` in the shell it is not set. I guess I should open a ticket for this, just wonder if this is something I'm doing wrong?

Take a look at the Ruby module on how to set the 2 env vars, using the devenv profile.

**Comment by terlar** [comment]
So I looked at that and got something working(ish):

This worked, but I had to explicitly add transient dependencies to my dependency list:
```
  env.OCAMLPATH = "${config.env.DEVENV_PROFILE}/lib/ocaml/${pkgs.ocamlPackages.ocaml.version}/site-lib/";
```

While this works:
```
nix-shell -p ocamlPackages.ocaml ocamlPackages.findlib ocamlPackages.base ocamlPack
ages.core_kernel ocamlPackages.ounit ocamlPackages.qcheck ocamlPackages.dune_3
```

I now had to add:
```
    pkgs.ocamlPackages.base
    pkgs.ocamlPackages.core_kernel
    pkgs.ocamlPackages.ounit
    pkgs.ocamlPackages.ounit2 # transient dep
    pkgs.ocamlPackages.qcheck
    pkgs.ocamlPackages.seq # transient dep
    pkgs.ocamlPackages.sexplib0 # transient dep
    pkgs.ocamlPackages.stdlib-shims #transient dep
```

I'm not that versed in the ocaml stuff, but I guess have to hack a bit more on it if not using the hook provided by `pkgs.ocamlPackages.findlib`.

Also if we implement this solution we need to make the ocaml packages configurable so the ocaml package is matching what the user provides.

**Comment by domenkozar** [comment]
See https://github.com/cachix/devenv/issues/45 for OCaml and how it needs to be extended for this to work

**Pull request merged**
