### PR TITLE
fix: improve mysql escaping

### LINKED ISSUE #483: mysql/mariadb error SQL when in password get '-'
**Describe the bug**

**To Reproduce**

In devenv.sh : 
[code in github gist](https://gist.github.com/Paul75/c4f4ca88e53e1f4a89ad3620b49a442c)

after do devenv up and get error : 

```
13:11:44 mysql-configure.1 | mysqld is alive
13:11:44 mysql-configure.1 | Creating initial database: sl-outil
13:11:44 mysql-configure.1 | Adding user: sl-outil
13:11:44 mysql-configure.1 | ERROR 1064 (42000) at line 2: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '-outil.* TO 'sl-outil'@'localhost'' at line 1
```

**Version**
 

0.6.2

### PR DESCRIPTION
**Pull request by shyim**
fixes #483

### CODE REVIEW

**Comment by Paul75** [comment]
not works : 

20:09:55 mysql-configure.1 | mysqld is alive
20:09:55 mysql-configure.1 | Creating initial database: sl-outil
20:09:55 mysql-configure.1 | Adding user: sl-outil
20:09:55 mysql-configure.1 | ERROR 1064 (42000) at line 2: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near ''sl-outil'.* TO 'sl-outil'@'localhost'' at line 1

**Comment by shyim** [comment]
it's not merged and released yet

**Comment by shyim** [comment]
@domenkozar can you retry something fails with nix setup?

**Comment by shyim** [comment]
I don't see a relation of failing CI to this changes. I rebased maybe helps

**Pull request merged**
