### PR TITLE
Add support for specifying JavaScript root directory

### PR DESCRIPTION
**Pull request by totoroot**
Motivation for these changes were mentioned in #993 and discussed in #899.

The changes allow for specifying a root directory for a JavaScript project. The directory can be specified as `languages.javascript.directory` and defaults to `config.devenv.root`, the root of the devenv project.

Also, I think it makes sense to use `nodejs-slim` as a default package instead of `nodejs`. This would mean a breaking change, as `nodejs-slim` does not include the npm package manager. However, with these changes it would be easy to enable either npm or [bun](https://bun.sh/), a different JavaScript runtime.

Please let me know whether additional changes are necessary.

### CODE REVIEW

**Comment by domenkozar** [comment]
from the directory test:

```
+ node -e 'require('\''axios'\'')'
node:internal/modules/cjs/loader:1147
  throw err;
  ^

Error: Cannot find module 'axios'
Require stack:
- /home/runner/work/devenv/devenv/examples/javascript-directory/[eval]
    at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
    at Module._load (node:internal/modules/cjs/loader:985:27)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
    at require (node:internal/modules/helpers:176:18)
    at [eval]:1:1
    at runScriptInThisContext (node:internal/vm:144:10)
    at node:internal/process/execution:109:14
    at [eval]-wrapper:6:24
    at runScript (node:internal/process/execution:92:62)
    at evalScript (node:internal/process/execution:123:10) {
  code: 'MODULE_NOT_FOUND',
  requireStack: [
    '/home/runner/work/devenv/devenv/examples/javascript-directory/[eval]'
  ]
}
```

**Comment by totoroot** [comment]
I forg

> from the directory test:
> 
> ```
> + node -e 'require('\''axios'\'')'
> node:internal/modules/cjs/loader:1147
>   throw err;
>   ^
> 
> Error: Cannot find module 'axios'
> Require stack:
> - /home/runner/work/devenv/devenv/examples/javascript-directory/[eval]
>     at Module._resolveFilename (node:internal/modules/cjs/loader:1144:15)
>     at Module._load (node:internal/modules/cjs/loader:985:27)
>     at Module.require (node:internal/modules/cjs/loader:1235:19)
>     at require (node:internal/modules/helpers:176:18)
>     at [eval]:1:1
>     at runScriptInThisContext (node:internal/vm:144:10)
>     at node:internal/process/execution:109:14
>     at [eval]-wrapper:6:24
>     at runScript (node:internal/process/execution:92:62)
>     at evalScript (node:internal/process/execution:123:10) {
>   code: 'MODULE_NOT_FOUND',
>   requireStack: [
>     '/home/runner/work/devenv/devenv/examples/javascript-directory/[eval]'
>   ]
> }
> ```

Whoops, I forgot to add a `cd directory` to the test.
As far as I'm aware, you cannot pass a working directory to the `node` command. While `npm` and `bun` have the `--prefix` and `--cwd` arguments, `node` can only be run in the current working directory.

Updated the PR.

**Comment by totoroot** [comment]
I'll probably add `pnpm` and `yarn` as well.

**Comment by domenkozar** [comment]
Oh you need to remove devenv.lock :)

**Comment by totoroot** [comment]
> Oh you need to remove devenv.lock :)

For all examples, should `devenv.lock` not be committed but also not be listed in the `.gitignore`? :thinking:

**Comment by domenkozar** [comment]
Exactly, planning to fix this soon but that's how it works for now

**Comment by totoroot** [comment]
I messed up the Git history a little, so I had to fix it, but with these latest changes, all popular JavaScript runtimes are available in devenv.

Later on I might add more options to the individual runtimes, but for now you can setup and install your JavaScript projects with either `npm`, `pnpm`, `yarn` or `bun`.

For `bun` I have for now decided to use the `--yarn` option, as it leads to a regular lock file that is compatible with yarn as well. By default `bun` uses a binary as a lock file.

Ready for review

**Pull request merged**
