### PR TITLE
feat: Add fortran language support

### PR DESCRIPTION
**Pull request by k3yss**
This PR adds support for fortran language in devenv project:

The following language features are added:
1. A default fortran compiler `gfortran` with an option to use your own version from nix repository
2. `fortran-fpm` a popular fortran package manager
3.  `fortran-language-server` LSP support for fortran.

### CODE REVIEW

**Comment by k3yss** [comment]
Hey, @domenkozar am I going in the right direction with this PR? Should I start adding docs as well?

**Comment by domenkozar** [comment]
Looks good, before we can merge we need to wait for tests to be sorted out so that I can see it works well on different platforms.

**Comment by domenkozar** [comment]
Can you rebase on top of main?

**Comment by k3yss** [comment]
> Can you rebase on top of main?

Done : )

**Pull request merged**
