### PR TITLE
feat(shell): revert from naked shell to pkgs.mkShell + unsetting irrelevant env vars

### PR DESCRIPTION
**Pull request by thenonameguy**
closes https://github.com/cachix/devenv/pull/498
fixes https://github.com/cachix/devenv/issues/497

### CODE REVIEW

**Comment by aaronmondal** [comment]
Also fixes https://github.com/cachix/devenv/issues/486.

**Comment by aaronmondal** [comment]
Ok I tested this against the flake in [rules_ll](https://github.com/eomii/rules_ll) and things seem to work fine. This change of course leads to more environment variables being set than before, but at least we know that it won't break existing more "exotic" C++ toolchains 😊

**Comment by domenkozar** [comment]
It seems that Nim is broken in nixpkgs, not here: https://hydra.nixos.org/build/213226629

**Comment by thenonameguy** [comment]
> It seems that Nim is broken in nixpkgs, not here: https://hydra.nixos.org/build/213226629
> 
> Possible fix [NixOS/nixpkgs#222285](https://github.com/NixOS/nixpkgs/pull/222285)

Thanks, I removed irrelevant change.

**Comment by sandangel** [comment]
Also my neovim could not find `tsserver` installed by `languages.typescript.enable = true;`. It was working when I use the standard `mkShell`.

**Comment by hurricanehrndz** [comment]
Although this patch addresses a lot of issues I am still seeing some issues on nix-darwin, specifically with CoreFoundation.

**Comment by sandangel** [comment]
Hi, sorry may I ask is there any update on this PR?

**Comment by domenkozar** [comment]
I mainly would like people to test it thoroughly before it's merged.

**Comment by sandangel** [comment]
I think it will be easier for people to test if we merge after all the CI check passed. If there is any issue, we can create a PR to fix. WDYT?

**Comment by aaronmondal** [comment]
I was actually wondering: What are the benefits of unsetting all those environment variables? I didn't really get the "keep it lean" comment.

**Comment by sandangel** [comment]
Hi, how long do we expect people to test this out before merging?

**Comment by bobvanderlinden** [comment]
I've updated this branch in my fork: https://github.com/bobvanderlinden/devenv/tree/feat/stripped-shell

There will be some regressions when merging this. Question is whether that is a good thing (honestly do not know).

With `mkNamedShell`, `LD_LIBRARY_PATH` was set based on `packages`. This is not the case anymore. This is partly a good thing, as I think setting potentially 'injecting' many libraries using `LD_LIBRARY_PATH` will cause problems like https://github.com/cachix/devenv/issues/555.

This is why the `python-poetry` example needed a change:

https://github.com/bobvanderlinden/devenv/commit/b669f22a471e06fd356e04b5b63cbb2da5fe5e2e#diff-3ea46e5d7bf8933097511b155be31bf25b2c6e01081c6d9a6dfe61624717082aR4

Question is whether setting `LD_LIBRARY_PATH` inside `mkShell` should now be added again.

Maybe as an alternative we should introduce a different option. Something like `runtimeLibraries = [ pkgs.zlib ]` instead of `packages = [ pkgs.zlib ]`, which is meant to solely set `LD_LIBRARY_PATH` and `DYLD_LIBRARY_PATH`. People can still use it, but need to do so more explicitly.

The real solution is for people to not rely on pre-built binaries, but I think that's the world we live in right now. `devenv` is a good middleground for that.

**Comment by aaronmondal** [comment]
`LD_LIBRARY_PATH` should [not be set at all if possible](http://xahlee.info/UnixResource_dir/_/ldpath.html). I think the linked python-poetry change is desirable.

> Maybe as an alternative we should introduce a different option. Something like runtimeLibraries = [ pkgs.zlib ] instead of packages = [ pkgs.zlib ], which is meant to solely set LD_LIBRARY_PATH and DYLD_LIBRARY_PATH. People can still use it, but need to do so more explicitly.

IMO it's risky to let users unknowningly manipulate these variables, but if it's explicit it could be a viable option. Though I wonder whether such an option is actually necessary. Personally, I think I'd prefer explicitly setting `LD_LIBRARY_PATH="${somepackage}/lib/"` manually or do something similar to what you did in python-poetry.

**Comment by bobvanderlinden** [comment]
> is it possible now to add openssl dev deps?

Yes, the packages are added as `nativeBuildInputs`.

See https://github.com/NixOS/nixpkgs/blob/3ed18a352739221ebaba0d11c38a2158faa29887/pkgs/build-support/mkshell/default.nix#L37

> Personally, I think I'd prefer explicitly setting `LD_LIBRARY_PATH="${somepackage}/lib/"` manually or do something similar to what you did in python-poetry.

There are people already relying on just adding runtime libraries as packages. Having a separate option for runtimeLibraries will make it a bit clearer how to migrate. It also allows to document what it does and why it is a bad idea to use it. The specific use-cases where it's the only option is also good to mention in the docs.

I agree it's a bad idea in general, but shipping binaries is the underlying problem. That's sometimes quite hard to get around when using ruby/python/node package managers.

**Comment by asymmetric** [comment]
This seems like the right thing to do. Setting `LD_LIBRARY_PATH` comes with troubling consequences, which are additionally quite hard to debug unless one knows already what's going on.

**Comment by domenkozar** [comment]
I've done testing today on examples on top of #745 and python-poetry example fails with

```
+ poetry run python -c 'import numpy'
Traceback (most recent call last):
  File "/tmp/python-poetry_nj6_mkml/.venv/lib/python3.10/site-packages/numpy/core/__init__.py", line 23, in <module>
    from . import multiarray
  File "/tmp/python-poetry_nj6_mkml/.venv/lib/python3.10/site-packages/numpy/core/multiarray.py", line 10, in <module>
    from . import overrides
  File "/tmp/python-poetry_nj6_mkml/.venv/lib/python3.10/site-packages/numpy/core/overrides.py", line 6, in <module>
    from numpy.core._multiarray_umath import (
ImportError: libz.so.1: cannot open shared object file: No such file or directory
```

We'll need to fix this one, any ideas? I tried adding `pkgconfig` to the deps and explicilty setting `zlib.dev` as a package.

**Comment by thenonameguy** [comment]
Great, thanks for bringing this forward. Closing this PR.

**Comment by domenkozar** [comment]
Thank you for making this happen :heart:

**Comment by cameronraysmith** [comment]
I imagine

<details><summary>this instance of zlib.h not found</summary>
<p>

  creating build/temp.linux-x86_64-cpython-310/pybedtools/include
  gcc -Wno-unused-result -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -I/nix/store/ixvka49i2mjnxzk8l8anykc1idilws1r-libxcrypt-4.4.36/include -fPIC -Ipybedtools/include/ -I/tmp/tmpd_84vc8x/.venv/include -I/nix/store/50kabpj0s79040a42b7jj2dxn85wmbfd-python3-3.10.13/include/python3.10 -c pybedtools/cbedtools.cpp -o build/temp.linux-x86_64-cpython-310/pybedtools/cbedtools.o
  In file included from pybedtools/include/bedFile.h:16,
                   from pybedtools/cbedtools.cpp:802:
  pybedtools/include/gzstream.h:35:10: fatal error: zlib.h: No such file or directory
     35 | #include <zlib.h>
        |          ^~~~~~~~
  compilation terminated.
  error: command '/nix/store/6jnx2r93796cnqr5dznrgc1bwgyl488b-devenv-profile/bin/gcc' failed with exit code 1
  

  at /nix/store/1hhzpyy8rvjavf894qy0r98hq8ah59qb-python3.11-poetry-1.7.1/lib/python3.11/site-packages/poetry/installation/chef.py:164 in _prepare
      160│ 
      161│                 error = ChefBuildError("\n\n".join(message_parts))
      162│ 
      163│             if error is not None:
    → 164│                 raise error from None
      165│ 
      166│             return path
      167│ 
      168│     def _prepare_sdist(self, archive: Path, destination: Path | None = None) -> Path:

Note: This error originates from the build backend, and is likely not a problem with poetry but with pybedtools (0.9.1) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "pybedtools (==0.9.1)"'.

</p>
</details> 

is another of https://github.com/cachix/devenv/pull/507#issuecomment-1660105656,

in this case, from

<details><summary>devenv devshell in flake.nix + pyproject.toml.</summary>
<p>

```nix
    devShells =
      forEachSystem
      (system: let
        pkgs = nixpkgs.legacyPackages.${system};
      in {
        default = devenv.lib.mkShell {
          inherit inputs pkgs;
          modules = [
            {
              packages = with pkgs; [
                atuin
                bat
                bedtools
                gcc
                gh
                git
                gnumake
                htslib
                lazygit
                poethepoet
                ripgrep
                starship
                tree
                zlib
                zlib.dev
                zsh
              ];

              dotenv = {
                enable = true;
                filename = ".env";
                # disableHint = true;
              };

              pre-commit.hooks = {
                alejandra.enable = true;
                ruff.enable = true;
                pyright.enable = true;
              };

              difftastic.enable = true;

              languages.python = {
                enable = true;
                package = pkgs.python310;
                poetry = {
                  enable = true;
                  activate.enable = true;
                  install = {
                    enable = true;
                    installRootPackage = true;
                    groups = [
                      "lint"
                      "test"
                      "docs"
                      "workflows"
                    ];
                  };
                };
              };
            }
          ];
        };
      });
```

with

```toml
[tool.poetry.dependencies]
pybedtools = "0.9.1"
```

</p>
</details> 

If this isn't a mistake, is there a recommended workaround?

**Pull request closed without merging**
