### PR TITLE
devenv-run-tests: switch directories in between tests

### PR DESCRIPTION
**Pull request by sandydoo**

### CODE REVIEW

**Comment by sandydoo** [comment]
I've figured out what's going on with this test. `git-hooks` installs the hooks in the `git` root dir, so the test/example hooks end up running against the whole devenv repo.
Either we add some tweakable option to `git-hooks`, or we could `cp` the whole  directory with the test/example to `tmp`, run `git init`, and do our stuff without worry.

**Comment by domenkozar** [comment]
Maybe we just need to `git init`?

**Comment by sandydoo** [comment]
> Maybe we just need to `git init`?

Yes, but it would be best to do so in a temporary directory.

**Comment by sandydoo** [comment]
This doesn't fully fix the wasm test, but it's a good cleanup to merge.

**Pull request merged**
