### PR TITLE
Allow module imports from devenv inputs

### PR DESCRIPTION
**Pull request by ankhers**
Previously the module import was only being checked for local files (i.e., an import prefixed by ./). This now includes an additional check for when we are importing something from an input that also ends in .nix which should import that file.

### CODE REVIEW

**Comment by ankhers** [comment]
This will resolve #833

**Comment by ankhers** [comment]
Note that I did not actually test this change. I was unsure how to go about that.

**Comment by domenkozar** [comment]
Could you add a test to `examples/imports/devenv.yaml` and document it at `docs/reference/yaml-options.md`?

**Comment by domenkozar** [comment]
Ping :)

**Comment by ankhers** [comment]
Do you have a repo that you would like to use for the import? I think it would be preferable to be something owned by the cachix org.

**Comment by ankhers** [comment]
ping

**Comment by domenkozar** [comment]
Thanks - added in 4e446c65d2295d12d1503424aa352d28e7e32c7b

**Pull request closed without merging**
