### PR TITLE
add devenv info command

### PR DESCRIPTION
**Pull request by domenkozar**
```shell-session
$ devenv info
Inputs:
├───devenv: path:./src/modules
├───nix: github:domenkozar/nix/05c8b261e0b7848cc02c736d59316d7e02be8514
│   ├───lowdown-src: github:kristapsdz/lowdown/d2c2b44ff6c27b936ec27358a2653caaef8f73b8
│   ├───nixpkgs: github:NixOS/nixpkgs/365e1b3a859281cf11b94f87231adeabbdd878a2
│   └───nixpkgs-regression: github:NixOS/nixpkgs/215d4d0fd80ca5163643b03a33fde804a29cc1e2
├───nixpkgs: github:NixOS/nixpkgs/c6e5939c8fa2ab2230baf1378a34746e8db1aed7
└───pre-commit-hooks: github:cachix/pre-commit-hooks.nix/46fb5634676994bd333a94c8bd322eb1854ff223
    ├───flake-utils: github:numtide/flake-utils/6ee9ebb6b1ee695d2cacc4faa053a7b9baa76817
    └───nixpkgs follows input 'nixpkgs'

# env
- DEVENV_DOTFILE: /home/domen/dev/cachix/devenv/.devenv
- DEVENV_ROOT: /home/domen/dev/cachix/devenv
- DEVENV_STATE: /home/domen/dev/cachix/devenv/.devenv/state

# packages
- python3.10-pre-commit-2.20.0
- devenv
- python3.10-virtualenv-20.16.5
- python3.10-cairocffi-1.4.0
- yaml2json-1.3

# scripts
- bump-version
- generate-doc-options
- generate-languages-example
- run-devenv-tests

# processes
- build: /nix/store/hpdm9ar9vp6fiihj23lfa38z526jac9x-watchexec-1.20.6/bin/watchexec -e nix nix build
- docs: bin/mkdocs serve
```

### CODE REVIEW

**Review by bobvanderlinden — APPROVED** [review]
Looks good to me! 👍

The process and env values can become quite long, but could be useful still.

The package name not always being consistent with the attribute name is a separate problem, but it is good enough how it is right now.

**Comment by shyim** [comment]
Maybe list also the inputs with their commit hash? 🤔

**Comment by domenkozar** [comment]
It's not the best since it's not consistent, but it shows the info about inputs now.

**Comment by domenkozar** [comment]
Merging for now, still open for feedback what to improve :)

**Pull request merged**
