### PR TITLE
docs(phoenix): add example for elixir phoenix

### PR DESCRIPTION
**Pull request by sevillaarvin**
This is my attempt for an elixir phoenix example.

Based on the ruby on rails example: https://github.com/cachix/devenv/commit/8d246b0c01721c546cdef6786560e5bd1ffae689 

Some differences I noted were:
- Rails uses unix domain socket by default [and also defaults to username: "$USER" and password: ""](https://stackoverflow.com/a/24039062), while phoenix has a default `username: "postgres" and password: "postgres"`.
  So what I did was to make postgres listen to `127.0.0.1`, then modify the config/dev.exs to use `username: "$USER" and password: ""`
- There's no project/bin in the phoenix project.
  As a workaround, I made `processes.phoenix.exec` cd into the project first before running the create database and start server commands

### CODE REVIEW

**Comment by domenkozar** [comment]
I'm going to have to mark this one as failed as part of #1005, could you take a look?

**Comment by sevillaarvin** [comment]
> I'm going to have to mark this one as failed as part of #1005, could you take a look?

Hi, I tried installing the new devenv as instructed

```sh
$ nix --extra-experimental-features flakes --extra-experimental-features nix-command profile install --accept-flake-config tarball+https://install.devenv.sh/rust-rewrite
```

then replaced the devenv.yaml file in devenv/examples/phoenix/devenv.yaml
```yaml
inputs:
  devenv:
    url: github:cachix/devenv/rust-rewrite
```

but about 15-20 mins during compilation my terminal gets killed by OOM
```
Mar 19 13:01:03 nixos kernel: oom-kill:constraint=CONSTRAINT_NONE,nodemask=(null),cpuset=nix-daemon.service,mems_allowed=0,global_oom,task_memcg=/user.slice/u>
Mar 19 13:01:03 nixos kernel: Out of memory: Killed process 5416 (nix) total-vm:666044kB, anon-rss:263676kB, file-rss:0kB, shmem-rss:0kB, UID:1000 pgtables:66>
Mar 19 13:01:03 nixos systemd[1577]: vte-spawn-a794692f-e797-4042-a9c3-32aebe5980fc.scope: A process of this unit has been killed by the OOM killer.
```

I tried three times, not really sure what to do next 😭

**Comment by domenkozar** [comment]
`cachix use cachix` to get the binary cache setup

**Comment by sevillaarvin** [comment]
> `cachix use cachix` to get the binary cache setup

Got it, thanks! Here's the new PR https://github.com/cachix/devenv/pull/1012.

**Pull request merged**
