### PR TITLE
rust: evaluate $DEVENV_PROFILE at runtime instead of in nix

### LINKED ISSUE #580: Infinite recursion error on macOS for Rust language and processes config
**Describe the bug**
After setting up a new project using `nix flake init --template github:cachix/devenv` after having installed `direnv` and `nix-direnv`, the devenv shell fails to initialize if Rust language support is enabled _and_ any process is defined.

```bash
direnv: loading ~/Projects/test/.envrc
direnv: using flake . --impure
error: infinite recursion encountered

       at /nix/store/z23x3la7s4ghznq0r9h1vihrmmc4gqg1-source/src/modules/languages/rust.nix:66:35:

           65|       env.RUSTDOCFLAGS = [ "-L framework=${config.env.DEVENV_PROFILE}/Library/Frameworks" ];
           66|       env.CFLAGS = [ "-iframework ${config.env.DEVENV_PROFILE}/Library/Frameworks" ];
             |                                   ^
           67|     })
(use '--show-trace' to show detailed location information)
realpath: /Users/kaiba/Projects/test/.direnv/flake-profile.41320: No such file or directory
direnv: nix-direnv: renewed cache
```

**To reproduce**
```
# .envrc
if ! has nix_direnv_version || ! nix_direnv_version 2.2.1; then
  source_url "https://raw.githubusercontent.com/nix-community/nix-direnv/2.2.1/direnvrc" "sha256-zelF0vLbEl5uaqrfIzbgNzJWGmLzCmYAkInj/LNxvKs="
fi

nix_direnv_watch_file devenv.nix
nix_direnv_watch_file devenv.lock
nix_direnv_watch_file devenv.yaml
if ! use flake . --impure
then
  echo "devenv could not be build. The devenv environment was not loaded. Make the necessary changes to devenv.nix and hit enter to try again." >&2
fi
```

```nix
# flake.nix
{
  inputs = {
    nixpkgs.url = "github:NixOS/nixpkgs/nixos-22.11";
    systems.url = "github:nix-systems/default";
    devenv.url = "github:cachix/devenv";
  };

  outputs = { self, nixpkgs, devenv, systems, ... } @ inputs:
    let
      forEachSystem = nixpkgs.lib.genAttrs (import systems);
    in
    {
      devShells = forEachSystem
        (system:
          let
            pkgs = nixpkgs.legacyPackages.${system};
          in
          {
            default = devenv.lib.mkShell {
              inherit inputs pkgs;
              modules = [
                {
                  # https://devenv.sh/reference/options/
                  packages = [ pkgs.hello ];

                  
                  # Adding these three lines will result in an infinite recursion error
                  #####################################################################
                  processes = {
                    anything.exec = "ls";
                  };
                  languages.rust.enable = true;
                  #####################################################################

                  enterShell = ''
                    hello
                  '';
                }
              ];
            };
          });
    };
}
```

**Version**
`devenv: 0.6.2`
`nix (Nix) 2.13.3`
`macOS 13.2.1 BuildVersion 22D68`

### PR DESCRIPTION
**Pull request by kaiba42**
Fixes #580. This appears to be another instance of the underlying issue causing #558 and #396.

"This fixes an infinite recursion error that originated as a result of trying to set an environment variable using the output of another environment variable." - @anoadragon453

### CODE REVIEW

**Comment by anoadragon453** [comment]
Heads up that @bobvanderlinden left a note at https://github.com/cachix/devenv/commit/75b18d276b66719bd4e6730dc56c8d39bdcbde59#r111783708 mentioning that this should probably be set in `enterShell` instead of via `env`, as otherwise this solution relies on the `DEVENV_PROFILE` environment variable being properly set in the user's shell at all times.

**Comment by bobvanderlinden** [comment]
Thanks for the heads-up! The PR that fixed the earlier issue is here for Python: https://github.com/cachix/devenv/pull/573

See that PR also for the ability to add tests in `.test.sh` in order to avoid regressions in the future.

**Comment by anoadragon453** [comment]
@bobvanderlinden Oh, I hadn't seen that. Thank you for doing that!

**Comment by domenkozar** [comment]
Did anyone test if this works?

**Comment by averagechris** [comment]
I worked around this on macOS via 
```
      env =
        {}
        // lib.mkIf pkgs.stdenv.isDarwin {
          RUSTFLAGS = lib.mkForce ["-L framework=$DEVENV_PROFILE/Library/Frameworks"];
          RUSTDOCFLAGS = lib.mkForce ["-L framework=$DEVENV_PROFILE/Library/Frameworks"];
          CFLAGS = lib.mkForce ["-iframework $DEVENV_PROFILE/Library/Frameworks"];
        };
```
which is equivalent to this PR.

**Comment by bobvanderlinden** [comment]
I think this will never work with the current implementation. Using `$DEVENV_PROFILE` inside `env.*` will not be expanded (or has that been changed in the meantime?). Adding it to `enterShell` does work.
Best would be to add a test, so that these kinds of problems won't pop up again and it is clear for others how to replicate them.

**Comment by averagechris** [comment]
@bobvanderlinden thanks you are absolutely correct. I'll open up a PR that mimics your solution for python. Thank you!

**Comment by domenkozar** [comment]
This one won't fix it, there's a new PR and I'm testing a more general fix.

**Pull request closed without merging**
