### PR TITLE
caddy: use mainProgram for binary

### PR DESCRIPTION
**Pull request by shyim**
This allows exchanging caddy with a different caddy built binary but different program name. Example frankenphp in nixpkgs

I had to update the devenv.lock as in that commit that mainProgram wasn't added in nixpkgs.

### CODE REVIEW

**Comment by domenkozar** [comment]
>   https://www.shellcheck.net/wiki/SC2064 -- Use single quotes, otherwise this...
       >   https://www.shellcheck.net/wiki/SC3010 -- In POSIX sh, [[ ]] is undefined.
       >
       > In examples/mailpit/.test.sh line 6:
       > trap "pkill -P $DEVENV_PID" EXIT
       >                ^---------^ SC2064 (warning): Use single quotes, otherwise this expands now rather than when signalled.
       >
       > For more information:
       >   https://www.shellcheck.net/wiki/SC2064 -- Use single quotes, otherwise this...
       >

**Comment by shyim** [comment]
I fixed the failure in mailpit. I think it was because shellcheck got updated with the lock file change

**Comment by domenkozar** [comment]
There's more failures

**Comment by shyim** [comment]
I unified all tests scripts now:
- fixed all shell checks errors
- use always trap to stop `devenv up`
- use same shebang for all scripts

**Comment by domenkozar** [comment]
last 10 log lines:
       >   https://www.shellcheck.net/wiki/SC1091 -- Not following: /nix/var/nix/profi...
       >   https://www.shellcheck.net/wiki/SC2181 -- Check exit code directly with e.g...
       >
       > In build_cloudflare.sh line 1:
       > set -xe
       > ^-- SC2148 (error): Tips depend on target shell and yours is unknown. Add a shebang or a 'shell' directive.
       >
       > For more information:
       >   https://www.shellcheck.net/wiki/SC2148 -- Tips depend on target shell and y...
       >
       For full logs, run 'nix log /nix/store/96b5m76d34iz50bar5hzqn6k467l32a2-pre-commit-run.drv'.

**Comment by shyim** [comment]
So `devenv ci` now runs without errors

**Comment by shyim** [comment]
Looks the gitignore change of examples broke almost all things

**Comment by shyim** [comment]
That flag fixed it. Can you trigger again the pipeline?

**Comment by shyim** [comment]
I had to revert the ignoring of devenv.lock. I think we would need to adjust nix itself? to not run `git add` on it. 🙈

**Comment by shyim** [comment]
So I fixed clickhouse, vault, modern-c, supported-languages. There is now something failing with ruby and rails. I have there no experience.

But more jobs are green than current main branch 😅

**Comment by domenkozar** [comment]
Thanks for fixing those :heart:

**Pull request merged**
