### PR TITLE
Make rust.nix accept toolchain options.

### PR DESCRIPTION
**Pull request by nothingnesses**
This makes the Rust option accept toolchain override options in a similar format to [rust-toolchain.toml](https://rust-lang.github.io/rustup/overrides.html#the-toolchain-file), which should be more familiar to Rust users and allow adding arbitrary components and targets, and is a step forward to addressing #530.

Changes:
* Remove `languages.rust.packages` and `languages.rust.version` options.
* Make nix-community/fenix a hard-requirement for `languages.rust.enable`.
* Add `languages.rust.toolchain` option.

~~This no longer includes rust-src by default and no longer has pre-commit hooks since the components may no longer be present. How should I handle rust-src and the pre-commit hooks instead?~~

According to the nix-community/fenix maintainer, rust-analyzer will automatically use the rust-src package if it exists. I've pushed a commit which causes the pre-commit hooks to use the rust components if they are added by the user, otherwise it defaults to the ones from nixpkgs.

[Matrix conversation about the topic](https://matrix.to/#/!plrRoZsBTUYBWzvzIq:matrix.org/$YPphSP3OyUVegK01ZV5MLjECbhHiEOL8buqzCytiNJc?via=matrix.org&via=glorifiedgluer.com&via=kde.org).

### CODE REVIEW

**Comment by nothingnesses** [comment]
I've updated my branch with [a commit to address the failing tests](https://github.com/nothingnesses/devenv/commit/0a5dab77c7aa7a6ae763c26fa6a5a6a85b1e3674), but it doesn't seem like the latest commit being used in this PR.

**Comment by nothingnesses** [comment]
I've added a commit to fix the failing tests, but I think the test will fail again when Rust updates which will require a new `sha256` value. I haven't managed to come up with a good way to automatically generate these.

**Comment by nothingnesses** [comment]
It seems like the only failing test related to Rust is now due to the VM running out of storage space (I think the rest of the errors are related to Racket instead). I'm wondering if maybe enabling cachix for fenix as per [these instructions](https://github.com/nix-community/fenix/tree/6e6a94c4d0cac4821b6452fbae46609b89a8ddcf#fenix) and using [cachix-actions](https://github.com/marketplace/actions/cachix) would help alleviate this. @figsoda Are derivations produced by the `fromToolchainFile` function cached and do you think it's worth trying this?

**Comment by figsoda** [comment]
> Are derivation outputs produced by the fromToolchainFile function cached in fenix's cachix

they are not, only outputs that are derivations (without needing a function call) are cached

> and do you think it's worth trying this?

I'm not sure if this is possible, since `fromToolchainFile` allows way too many permutations for all of them to be cached

**Comment by nothingnesses** [comment]
Closing in favour of #667.

**Pull request closed without merging**
