### PR TITLE
Make env a submodule

### PR DESCRIPTION
**Pull request by Atry**
As suggested by https://github.com/cachix/devenv/pull/566#issuecomment-1534726930, this PR let `env.DEVENV_ROOT` be overridable.

### CODE REVIEW

**Comment by domenkozar** [comment]
Can you rebase?

**Comment by Atry** [comment]
Rebased

**Comment by enobayram** [comment]
Thanks @Atry, I was just about to open a similar PR, I think this change makes `devenv` applicable to a new set of use cases.

**Comment by domenkozar** [comment]
It seems that docs fail to build, can you take a look? Run `devenv up` on the repo.

**Comment by Atry** [comment]
@domenkozar Could you trigger CI?

**Comment by domenkozar** [comment]
See what I did in https://github.com/cachix/devenv/pull/707 so that we can get rid of infinite recursive errors. Is submodule still needed?

**Comment by Atry** [comment]
I think it's still a good feature to allow for typed environment variables

**Pull request merged**
