### PR TITLE
Add missing hello package

### PR DESCRIPTION
**Pull request by shyim**
Everytime I run `devenv init` I wonder why I have missing command hello 😅 

image

### CODE REVIEW

**Comment by domenkozar** [comment]
I'd rather uncomment line 19 and move it a bit up over the comments, since that was the reason to demonstrate hello :)

**Comment by shyim** [comment]
and deletee it from the enterShell?

**Comment by domenkozar** [comment]
https://github.com/cachix/devenv/commit/c5b65be7623fab1c630840acaa75597e101f2082

**Comment by domenkozar** [comment]
Let me know if that doesn't fix it :)

**Pull request closed without merging**
