### PR TITLE
added: language support for forth using the gforth implementation

### PR DESCRIPTION
**Pull request by theesm**
This PR adds basic language support for Forth using the [Gforth](https://gforth.org/) implementation of Forth. As there are several implementations available in nixpkgs, such as:

- `pkgs._4th`
- `pkgs.pforth`

are there any best practices on how to make different implementations available for enabling in devenv?

### CODE REVIEW

**Comment by domenkozar** [comment]
It's best to list them in the documentation field of `package`.

**Comment by domenkozar** [comment]
@0pointerexception let me know if I'm being unclear here.

**Comment by 0pointerexception** [comment]
@domenkozar thanks for offering to clarify this, and sorry for the delay as I haven't had time lately to get back to this PR. By documentation field of `package` you mean referring to different implementations as a part of `description`?

**Comment by domenkozar** [comment]
Exactly :)

**Comment by 0pointerexception** [comment]
> Exactly :)

Done^^

**Comment by domenkozar** [comment]
Need to run pre-commit hook :)

**Comment by domenkozar** [comment]
ping

**Comment by 0pointerexception** [comment]
I'll get back to my PR later on today, sorry for the delay; wasn't that active on GH during the last months.

**Comment by domenkozar** [comment]
Ping

**Pull request closed without merging**
