### PR TITLE
Add Just Command Runner and Treefmt-nix; Fix Minor Bugs

### LINKED ISSUE #117: Adding commands to devenv
It would be interesting if there was a way to extend devenv commands. 

```nix
  commands.mysubcommand.exec = ''
    echo hello
  '';
```

And running it:

```
$ devenv mysubcommand
hello
````

Could be used with #103 for cli parsing.

### LINKED ISSUE #533: Integrate treefmt-nix
[`treefmt`](https://github.com/numtide/treefmt) is a CLI tool to format all files in a repository. It recurses through a directory and calls the right formatter based on the type of file it finds.

`treefmt` requires a configuration file that tells it what to execute for each file type. It doesn't include this configuration by default, so it takes some time to get the configuration right and requires knowledge of the different kinds of formatters that you'd like the use. Knowledge like which CLI flags to use.

[`treefmt-nix`](https://github.com/numtide/treefmt-nix) is a Nix module system to build a treefmt configuration. It includes options for most of the different formatters and allows just enabling them. The same kind of module system devenv uses.

For instance:

```nix
treefmt-nix.mkWrapper nixpkgs {
  # Used to find the project root
  projectRootFile = ".git/config";
  # Enable the terraform formatter
  programs.terraform.enable = true;
  # Override the default package
  programs.terraform.package = nixpkgs.terraform_1;
  # Override the default settings generated by the above option
  settings.formatter.terraform.excludes = [ "hello.tf" ];
}
```

It would be nice if this could be integrated into devenv, so that you could have options in devenv like:

```nix
services.treefmt.enable = true;
services.treefmt.programs.terraform.enable = true;
```

This probably requires adding treefmt-nix as a Nix flake input to devenv. Is this something we'd want?

### LINKED ISSUE #739: Print version information when entering shell
One thing I like doing is print version information when entering the shell of a new/different project. It tells me what tools I get for the project.

However, writing the version script over and over again results in a lot of duplications.

I propose adding a module that prints version information for already supported tools (eg. languages) and allows users to opt-in for displaying version information when entering a devshell.

Here is what I cooked up:

```nix
{ config, lib, ... }:

let
  cfg = config.versions;
in
{
  options.versions = {
    enable = lib.mkEnableOption "Print versions when entering a shell";

    exec = lib.mkOption {
      type = lib.types.lines;
      description = "Bash code to execute to print version information.";
      default = "";
    };
  };

  config = lib.mkIf cfg.enable {
    scripts = {
      versions.exec = cfg.exec;
    };

    enterShell = ''
      versions
    '';
  };
}
```

In case of Go, the integration would look like this:

```nix
  config = lib.mkIf cfg.enable {
    # ...
    versions.exec = "${cfg.package}/bin/go version";
  };
```

Would you be interested in adding such a module?

### PR DESCRIPTION
**Pull request by use-the-fork**
This pull request introduces the Just command runner and Treefmt-nix, and includes fixes for several minor bugs.

### Key Additions:
1. **Just Command Runner:**
   - Implements the Just command runner for seamless script integration.
   - Integrates with `pre-commit`, `treefmt-nix`, `devenv up`, and `version`.
   - Includes sample Just scripts for initial use and further development.
   - Adds the default `justfile`, which imports `just.flake` into `REQUIRED_FILES` for proper setup.
   - Updates documentation to include new options and settings for the Just command runner.

2. **Treefmt-nix:**
   - Integrates Treefmt-nix into `devenv`.
   - Updates documentation to detail the Treefmt-nix configuration and usage.

3. **Development Environment Updates (`devenv.nix`):**
   - Enhances the build process for documentation to avoid `npx` dependencies by using Nix's `pkgs.tailwindcss` package.

### Issues Addressed:
- Closes #117
- Closes #739
- Closes #533

### CODE REVIEW

**Comment by use-the-fork** [comment]
Let me know if there is anything you all need me to do with this module. I added docs and tests today.

**Comment by use-the-fork** [comment]
@domenkozar I'm not sure if I did everything you need to merge this. Just so you know, I use AI to help write the PR and commit messages. I do all the coding myself but AI does a better job at making my documentation clear :)

**Comment by I-Want-ToBelieve** [comment]
@domenkozar

**Comment by use-the-fork** [comment]
@sandydoo @domenkozar I'm very pleased with the current integration after today's refactor, which streamlined the just runner. I have other integrations ready in a separate branch for a PR, but I prefer to get this merged first. I understand it's a significant change and am eager to assist in any way needed.

So let me know thanks!

**Comment by domenkozar** [comment]
Hey, can you split this PR into separate ones for each issue? That way it makes it easier to review.

**Pull request closed without merging**
