### PR TITLE
feat(shell): add option to turn off naked shell implementation, disable for C compiler using languages

### PR DESCRIPTION
**Pull request by thenonameguy**
fixes https://github.com/cachix/devenv/issues/497

### CODE REVIEW

**Comment by thenonameguy** [comment]
Yup, makes sense, keeping cyclomatic complexity low is a great guide.

This branch was created to unblock my friend using devenv on M1 for a Rust project, therefore it is more on the fast implementation, than a well thought one :) 

It solved the problem for him, but of course we are back to square with the:
```
direnv: export +AR +AS +CC +CFLAGS +CONFIG_SHELL +CXX +DEVENV_DOTFILE +DEVENV_PROFILE +DEVENV_ROOT +DEVENV_STATE +HOST_PATH +IN_NIX_SHELL +LD +LD_DYLD_PATH +MACOSX_DEPLOYMENT_TARGET +NIX_BINTOOLS +NIX_BINTOOLS_WRAPPER_TARGET_HOST_aarch64_apple_darwin +NIX_BUILD_CORES +NIX_CC +NIX_CC_WRAPPER_TARGET_HOST_aarch64_apple_darwin +NIX_CFLAGS_COMPILE +NIX_COREFOUNDATION_RPATH +NIX_DONT_SET_RPATH +NIX_DONT_SET_RPATH_FOR_BUILD +NIX_ENFORCE_NO_NATIVE +NIX_HARDENING_ENABLE +NIX_IGNORE_LD_THROUGH_GCC +NIX_LDFLAGS +NIX_NO_SELF_RPATH +NIX_STORE +NM +PATH_LOCALE +RANLIB +RUSTDOCFLAGS +RUSTFLAGS +RUST_SRC_PATH +SIZE +SOURCE_DATE_EPOCH +STRINGS +STRIP +XDG_DATA_DIRS +__darwinAllowLocalNetworking +__impureHostDeps +__propagatedImpureHostDeps +__propagatedSandboxProfile +__sandboxProfile +__structuredAttrs +buildInputs +buildPhase +builder +cmakeFlags +configureFlags +depsBuildBuild +depsBuildBuildPropagated +depsBuildTarget +depsBuildTargetPropagated +depsHostHost +depsHostHostPropagated +depsTargetTarget +depsTargetTargetPropagated +doCheck +doInstallCheck +dontAddDisableDepTrack +mesonFlags +name +nativeBuildInputs +out +outputs +patches +phases +preferLocalBuild +propagatedBuildInputs +propagatedNativeBuildInputs +shell +shellHook +stdenv +strictDeps +system ~PATH
```
env var export list. I'll try the selective setup-hook running / language module approach over the weekend to find a better middle-ground.

**Comment by thenonameguy** [comment]
@domenkozar I tried implementing a change to naked shell, that runs the `preConfigureHooks` of the normal nix stdenv. Sadly couldn't get it to work. As an alternative, we could switch back to the `pkgs.mkShell` implementation and have a module configurable blocklist of `unset` env vars that we don't need.

**Comment by domenkozar** [comment]
Sounds good to me, that will reduce a lot of the complexities we're currently facing.

**Comment by thenonameguy** [comment]
Closing in favor of https://github.com/cachix/devenv/pull/507

**Pull request closed without merging**
