### PR TITLE
Yarn must the same package as language definition.

### PR DESCRIPTION
**Pull request by dz0ny**
Inherit a package, so that we do not end up with different versions of Node.js as default is whatever is marked as stable in Nixpkgs.

### CODE REVIEW

**Comment by domenkozar** [comment]
> error: syntax error, unexpected '=', expecting ';'

**Comment by domenkozar** [comment]
This example seems to fail: https://github.com/cachix/devenv/actions/runs/9872750941/job/27263894731?pr=1325#step:7:29

**Comment by domenkozar** [comment]
Ping

**Comment by dz0ny** [comment]
We ended with a configuration like this, but this is mostly because the project uses a lot of packages and there were issues with resolving correct ESM/non-ESM packages that older versions of Yarn had.

```nix
{
  inputs,
  ...
}: let
  nixpkgs-2405 = import inputs.nixpkgs-2405 {system = pkgs.stdenv.system;};
  node-20 = nixpkgs-2405.nodejs_20;
  yarn-422 = nixpkgs-2405.yarn-berry.override {
    nodejs = node-20;
  };
in {
  packages = with nixpkgs-2405; [
    yarn-422
    node-20
  ];
  languages.javascript.package = node-20;
}
```

**Comment by domenkozar** [comment]
Let's wait on the CI

**Review by Kutasy — APPROVED** [review]

**Comment by domenkozar** [comment]
@dz0ny can you rebase?

**Pull request merged**
