### PR TITLE
feat: add typesense service

### PR DESCRIPTION
**Pull request by shyim**

### CODE REVIEW

**Comment by domenkozar** [comment]
`pre-commit run -a`

**Comment by shyim** [comment]
I will look later. did run devenv shell and it wanted to download 9G. i am traveling 😂

**Comment by domenkozar** [comment]
Ping

**Comment by shyim** [comment]
The macos build may not pass, as the cachix nixpkgs is too old

**Comment by domenkozar** [comment]
ping

**Comment by shyim** [comment]
@domenkozar do I need to do something here really? 

```
❯ pre-commit run -a
generate-css.............................................................Passed
nixpkgs-fmt..............................................................Passed
rustfmt..................................................................Passed
```

The failing job is something completely different something with tailwindcss 🤔

**Comment by shyim** [comment]
I rebased maybe the ci result is then fixed

**Pull request merged**
