### PR TITLE
Nix 2.24

### PR DESCRIPTION
**Pull request by domenkozar**
Fixes https://github.com/cachix/devenv/issues/1364
Fixes https://github.com/NixOS/nix/issues/10647
Fixes https://github.com/cachix/devenv/issues/1114

### CODE REVIEW

**Comment by lf-** [comment]
I'm not sure the actual version here but the .version suggests it might be 2.24.0, which doesn't have this morning's security fix. Worth at least checking.

**Comment by domenkozar** [comment]
Hey, our versions don't really match upstream versions. I'm happy to make that clearer, open to ideas!

**Comment by lf-** [comment]
Yeah, I realize. I'm not sure how the git history was done so this may not actually be an issue but the "compare" button on GitHub seems to imply the fix patches may be missing from the branch; it's unclear. That's why I'm suggesting to check to make sure :)

**Comment by domenkozar** [comment]
https://github.com/domenkozar/nix/commits/devenv-2.24/

**Pull request merged**
